logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  mp:
    appId: wxd84d3230eb686234
    secret: 3997a7cc690500d61774312304b853dd
    token: wiki2link
    aesKey: kyZnHHulSl5IUHe4PlNrrxb4gsUM97NjGWAqeeED1ST
service:
  picRec: http://siki.top:8080/im2txt?url=
